version: "3"
services:
  dumdum:
    build: ./dapp
    depends_on:
      - keystone
    image: dizz/dumdum:latest
    links:
      - keystone
    environment:
      - ET_AAA_ESM_KEYSTONE_AUTH_URL=http://keystone:5000/v3
      - ET_AAA_ESM_KEYSTONE_USERNAME=admin
      - ET_AAA_ESM_KEYSTONE_PASSWD=admin
      - ET_AAA_ESM_KEYSTONE_TENANT=admin
    expose:
      - 56567
    ports:
      - "56567:56567"
    networks:
      - dumdum

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: shush
    networks:
      - dumdum

  keystone:
    depends_on:
      - mysql
    image: dizz/dock-os-keystone
    hostname: keystone
    links:
      - mysql
    ports:
      - "35357:35357"
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: shush
      ADMIN_TOKEN: admintokin
      ADMIN_TENANT_NAME: admin
      ADMIN_USER_NAME: admin
      ADMIN_PASSWORD: admin
    networks:
      - dumdum
              
networks:
  dumdum:
    driver: bridge

